In [1]:
%load_ext autoreload                                                                                                                                                      
%autoreload 2 
from get_scorecard import *
from get_standings import *
import warnings
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import argparse
import numpy as np
from helpers import *
from settings import *
warnings.simplefilter(action="ignore", category=FutureWarning)

pd.options.mode.chained_assignment = None

os.environ['SCRAPER_API_KEY'] = "67dd6af4b4c692a37a2a419b944aaef0"

2026-04-13 13:13:01.327 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-04-13 13:13:01.329 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-04-13 13:13:01.330 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

### Match Run

In [18]:
match_id = 1529268 
series_id = 8048
df = get_scorecard(series_id, match_id)
upload_df_to_gcs(df, f"Scorecards/{match_id}_scorecard.csv", bucket_name='summer-is-coming-2026')

Warning: Playing XI section not found; fielding points may be incomplete.

In [19]:
df

,index,Name_batting,Team_batting,Player_id,Desc,Runs_batting,Balls_batting,4s,6s,SR,...,base_points_bowling,pace_points_bowling,milestone_points_bowling,impact_points_bowling,bowling_points,Name,Team,fielding_points,bonus_points,total_points
0,0,Tim Seifert,1,625964,c Phillips b Rabada,19.0,14.0,2.0,1.0,135.71,...,0.0,0.0,0.0,0.0,0.0,Tim Seifert,1,0,0,28.0
1,1,Ajinkya Rahane,1,277916,c Rabada b Mohammed Siraj,0.0,1.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,Ajinkya Rahane,1,0,0,-6.0
2,2,Angkrish Raghuvanshi,1,1292495,c †Buttler b Rabada,8.0,4.0,2.0,0.0,200.00,...,0.0,0.0,0.0,0.0,0.0,Angkrish Raghuvanshi,1,0,0,14.0
3,3,Cameron Green,1,1076713,c †Buttler b Rashid Khan,79.0,55.0,7.0,4.0,143.63,...,0.0,0.0,0.0,0.0,0.0,Cameron Green,1,20,0,168.0
4,4,Rovman Powell,1,820351,c Mohammed Siraj b Ashok Sharma,27.0,20.0,2.0,2.0,135.00,...,0.0,0.0,0.0,0.0,0.0,Rovman Powell,1,0,0,50.0
5,5,Anukul Roy,1,1079839,c †Buttler b Prasidh Krishna,9.0,7.0,1.0,0.0,128.57,...,0.0,-1.0,0.0,4.0,3.0,Anukul Roy,1,0,0,15.0
6,6,Rinku Singh,1,723105,c †Buttler b Rabada,1.0,2.0,0.0,0.0,50.00,...,0.0,0.0,0.0,0.0,0.0,Rinku Singh,1,10,0,10.0
7,7,Ramandeep Singh,1,1079470,c Mohammed Siraj b Ashok Sharma,17.0,8.0,2.0,1.0,212.50,...,25.0,3.0,0.0,2.0,30.0,Ramandeep Singh,1,0,0,60.0
8,8,Sunil Narine,1,230558,c Phillips b Mohammed Siraj,0.0,5.0,0.0,0.0,0.00,...,25.0,24.0,0.0,16.0,65.0,Sunil Narine,1,0,0,55.0
9,9,Kartik Tyagi,1,1122918,run out (†Buttler/Prasidh Krishna),6.0,4.0,0.0,1.0,150.00,...,0.0,0.0,0.0,12.0,12.0,Kartik Tyagi,1,20,0,42.0
10,10,Vaibhav Arora,1,1209292,not out,0.0,1.0,0.0,0.0,0.00,...,25.0,3.0,0.0,10.0,38.0,Vaibhav Arora,1,0,0,37.0
11,11,Sai Sudharsan,2,1151288,c Kartik Tyagi b Narine,22.0,16.0,1.0,2.0,137.50,...,0.0,0.0,0.0,0.0,0.0,Sai Sudharsan,2,0,5,38.0
12,12,Shubman Gill,2,1070173,c Green b Arora,86.0,50.0,8.0,4.0,172.00,...,0.0,0.0,0.0,0.0,0.0,Shubman Gill,2,0,30,198.0
13,13,Jos Buttler,2,308967,c Green b Varun,25.0,15.0,2.0,2.0,166.66,...,0.0,0.0,0.0,0.0,0.0,Jos Buttler,2,50,5,106.0
14,14,Washington Sundar,2,719715,c Kartik Tyagi b Varun,13.0,13.0,1.0,0.0,100.00,...,0.0,0.0,0.0,0.0,0.0,Washington Sundar,2,0,5,19.0
15,15,Glenn Phillips,2,823509,c Singh b Ramandeep Singh,19.0,16.0,2.0,0.0,118.75,...,0.0,0.0,0.0,0.0,0.0,Glenn Phillips,2,20,5,49.0
16,16,Rahul Tewatia,2,423838,not out,7.0,6.0,0.0,0.0,116.66,...,0.0,0.0,0.0,0.0,0.0,Rahul Tewatia,2,0,5,13.0
17,17,M Shahrukh Khan,2,719719,not out,3.0,2.0,0.0,0.0,150.00,...,0.0,0.0,0.0,0.0,0.0,M Shahrukh Khan,2,0,5,9.0
18,18,Rashid Khan,2,793463,DNB,0.0,0.0,0.0,0.0,0,...,25.0,0.0,0.0,15.0,40.0,Rashid Khan,2,0,5,45.0
19,19,Ashok Sharma,2,1299879,DNB,0.0,0.0,0.0,0.0,0,...,50.0,0.0,10.0,16.0,76.0,Ashok Sharma,2,0,5,81.0
20,20,Kagiso Rabada,2,550215,DNB,0.0,0.0,0.0,0.0,0,...,75.0,21.0,20.0,20.0,136.0,Kagiso Rabada,2,10,5,151.0
21,21,Mohammed Siraj,2,940973,DNB,0.0,0.0,0.0,0.0,0,...,50.0,39.0,10.0,21.0,120.0,Mohammed Siraj,2,20,5,145.0
22,22,Prasidh Krishna,2,917159,0,0.0,0.0,0.0,0.0,0,...,25.0,12.0,0.0,12.0,49.0,Prasidh Krishna,2,10,5,64.0
23,23,Varun Chakravarthy,1,1108375,0,0.0,0.0,0.0,0.0,0,...,50.0,6.0,10.0,8.0,74.0,Varun Chakravarthy,1,0,0,74.0

In [24]:
scorecards = retrieve_scorecards()
weekly_dicts, squad_dict = retrieve_team_info()
(score_df, sum_df, cumsum_df, cumrank_df, standings_df, weekly_points_df, agg_points_df, season_points_df, weekly_player_points_df
) = create_score_df(
    scorecards, weekly_dicts, squad_dict, weeks, owner_team_dict, player_id_dict
)
save_outputs(
    score_df, sum_df, cumsum_df, cumrank_df, standings_df, weekly_points_df, agg_points_df, season_points_df, weekly_player_points_df
)

In [25]:
standings_df

     Owner                    Team  Points  Standings
0      Ash            Come on Ash!  3402.0        1.0
1    Srini             Jeipomda XI  3196.0        2.0
2     Shar     Budget Padmanabhans  3190.0        3.0
3     Firi           Fiery Dragons  3012.0        4.0
4     Bhar     Galactic Federation  2970.0        5.0
5    Jilla                J Kullis  2921.0        6.0
6     Abhi           Kovai Rousers  2812.0        7.0
7   Vaithy          Thayir Saadham  2787.0        8.0
8     Saju            The Wolfpack  2780.0        9.0
9   Siddhu        The Spartacus 11  2279.0       10.0
10   Mabbu  Malayoor Mambattiyaans  2259.0       11.0

In [21]:
standings_df

     Owner                    Team  Points  Standings
0      Ash            Come on Ash!  3402.0        1.0
1    Srini             Jeipomda XI  3196.0        2.0
2     Shar     Budget Padmanabhans  3143.0        3.0
3     Firi           Fiery Dragons  3012.0        4.0
4     Bhar     Galactic Federation  2970.0        5.0
5    Jilla                J Kullis  2898.0        6.0
6     Abhi           Kovai Rousers  2812.0        7.0
7   Vaithy          Thayir Saadham  2787.0        8.0
8     Saju            The Wolfpack  2780.0        9.0
9    Mabbu  Malayoor Mambattiyaans  2243.0       10.0
10  Siddhu        The Spartacus 11  2153.0       11.0

In [13]:
sum_df

,Owner,Match_1,Match_2,Match_3,Match_4,Match_5,Match_6,Match_7,Match_8,Match_9,...,Match_14,Match_15,Match_16,Match_17,Match_18,Match_19,Match_20,Match_21,Match_22,Match_23
0,Abhi,235.0,0.0,76.0,88.0,106.0,122.0,101.0,66.0,58.0,...,171.0,18.0,163.0,248.0,287.0,170.0,113.0,14.0,273.0,110.0
1,Ash,124.0,168.0,192.0,13.0,0.0,334.0,67.0,75.0,212.0,...,0.0,348.0,257.0,175.0,0.0,25.0,151.0,171.0,198.0,150.0
2,Bhar,128.0,49.0,131.0,102.0,-8.0,162.0,154.0,110.0,174.0,...,0.0,209.0,106.0,114.0,50.0,8.0,262.0,45.0,126.0,234.0
3,Firi,39.0,49.0,45.0,159.0,82.0,55.0,226.0,117.0,66.0,...,519.0,77.0,81.0,0.0,195.0,261.0,124.0,0.0,316.0,86.0
4,Jilla,20.0,298.0,255.0,118.0,81.0,16.0,77.0,78.0,99.0,...,181.0,163.0,333.0,-12.0,255.0,0.0,104.0,-9.0,148.0,38.0
5,Mabbu,0.0,93.0,70.0,268.0,11.0,0.0,215.0,14.0,165.0,...,203.0,0.0,15.0,227.0,0.0,194.0,138.0,127.0,0.0,0.0
6,Saju,89.0,14.0,152.0,157.0,216.0,46.0,208.0,142.0,82.0,...,118.0,31.0,111.0,226.0,82.0,72.0,0.0,92.0,113.0,119.0
7,Shar,107.0,70.0,69.0,158.0,144.0,34.0,226.0,367.0,225.0,...,89.0,0.0,309.0,317.0,22.0,204.0,237.0,26.0,24.0,108.0
8,Siddhu,170.0,167.0,37.0,18.0,208.0,328.0,-1.0,159.0,93.0,...,57.0,39.0,44.0,104.0,3.0,82.0,104.0,114.0,0.0,107.0
9,Srini,622.0,102.0,25.0,105.0,66.0,429.0,36.0,0.0,209.0,...,44.0,176.0,50.0,160.0,0.0,78.0,22.0,355.0,38.0,93.0
10,Vaithy,0.0,180.0,49.0,86.0,88.0,81.0,37.0,104.0,60.0,...,75.0,121.0,40.0,88.0,503.0,232.0,71.0,40.0,133.0,22.0

### Bench Subs

In [22]:
from get_bench_subs import suggest_bench_subs

week = 'Week3'  # <-- change to the week you want to analyse
suggest_bench_subs(week, scorecards, weekly_player_points_df)

2026-04-17 12:04:52.718 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-04-17 12:04:52.732 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-04-17 12:04:52.733 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

=== Bench Substitution Suggestions for Week3 ===

Jilla — J Kullis:
  OUT: Jacob Bethell                 IN: George Linde                  (+47 pts)
  XI check — can bat: 7  can bowl: 5  WK: 1  overseas: 3/4
  Suggested XI: Vaibhav Sooryavanshi, KL Rahul, Rohit Sharma, Ajinkya Rahane, George Linde, Rovman Powell, Harshal Patel, Varun Chakravarthy, Tim David, Jamie Overton, Vijaykumar Vyshak

Mabbu — Malayoor Mambattiyaans:
  OUT: Sai Kishore                   IN: Ashutosh Sharma               (+33 pts)
  XI check — can bat: 7  can bowl: 7  WK: 2  overseas: 4/4
  Suggested XI: Jos Buttler, Shreyas Iyer, Hardik Pandya, Marco Jansen, Trent Boult, Ashutosh Sharma, MS Dhoni, Mayank Markande, Nandre Burger, Shahbaz Ahmed, Tushar Deshpande

Shar — Budget Padmanabhans:
  OUT: Manimaran Siddharth           IN: Akeal Hosein                  (+94 pts)
  XI check — can bat: 9  can bowl: 5  WK: 1  overseas: 3/4
  Suggested XI: Priyansh Arya, Tilak Varma, Sameer Rizvi, Prasidh Krishna, Krunal Pandya, Ruturaj Gaikwad, Dhruv Jurel, Romario Shepherd, Sherfane Rutherford, Akeal Hosein, Shivang Kumar

Siddhu — The Spartacus 11:
  OUT: Shimron Hetmyer               IN: Rasikh Salam                  (+251 pts)
  XI check — can bat: 6  can bowl: 8  WK: 2  overseas: 3/4
  Suggested XI: Heinrich Klaasen, Suryakumar Yadav, Rasikh Salam, Kuldeep Yadav, Prince Yadav, Jaydev Unadkat, Shardul Thakur, Rahul Tewatia, Kartik Sharma, Mitchell Starc, Matthew Short

## Unsold Players

In [113]:
from settings import unsold_spreadsheet_url, bucket_name

download_gsheet_as_csv(unsold_spreadsheet_url, sheet_name = 'Unsold_players', download_folder="Unsold")
unsold_df = pd.read_csv("Unsold/Unsold_players.csv")
upload_df_to_gcs(unsold_df, "Unsold_players.csv", bucket_name=bucket_name)

Sheet 'Unsold_players' has been downloaded'

## Squads

In [23]:
from settings import squads_spreadsheet_url

week = 'Week3'

download_gsheet_as_csv(squads_spreadsheet_url, sheet_name = week, download_folder="Squads")
# squad_df = pd.read_csv(f"Squads/{week}.csv")
# upload_df_to_gcs(squad_df, f"Squads/{week}.csv", bucket_name=bucket_name)

Sheet 'Week3' has been downloaded'

## Trades

In [29]:
from settings import trades_spreadsheet_url, owner_team_dict

for owner in sorted(owner_team_dict.keys()):
    download_gsheet_as_csv(trades_spreadsheet_url, sheet_name = owner, download_folder="Trades")
    transfer_df = pd.read_csv(f"Trades/{owner}.csv")
    upload_df_to_gcs(transfer_df, f"Trades/{owner}.csv", bucket_name=bucket_name)

Sheet 'Abhi' has been downloaded'
Sheet 'Ash' has been downloaded'
Sheet 'Bhar' has been downloaded'
Sheet 'Firi' has been downloaded'
Sheet 'Jilla' has been downloaded'
Sheet 'Mabbu' has been downloaded'
Sheet 'Saju' has been downloaded'
Sheet 'Shar' has been downloaded'
Sheet 'Siddhu' has been downloaded'
Sheet 'Srini' has been downloaded'
Sheet 'Vaithy' has been downloaded'

#### Script to get player IDs

In [ ]:
headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
    }
squad_urls = {
  "csk":"https://www.espncricinfo.com/series/ipl-2026-1510719/chennai-super-kings-squad-1511148/series-squads",
  "dc":"https://www.espncricinfo.com/series/ipl-2026-1510719/delhi-capitals-squad-1511107/series-squads",
  "gt":"https://www.espncricinfo.com/series/ipl-2026-1510719/gujarat-titans-squad-1511094/series-squads",
  "kkr":"https://www.espncricinfo.com/series/ipl-2026-1510719/kolkata-knight-riders-squad-1511092/series-squads",
  "lsg":"https://www.espncricinfo.com/series/ipl-2026-1510719/lucknow-super-giants-squad-1511235/series-squads",
  "mi":"https://www.espncricinfo.com/series/ipl-2026-1510719/mumbai-indians-squad-1511109/series-squads",
  "pk":"https://www.espncricinfo.com/series/ipl-2026-1510719/punjab-kings-squad-1511082/series-squads",
  "rr":"https://www.espncricinfo.com/series/ipl-2026-1510719/rajasthan-royals-squad-1511089/series-squads",
  "rcb":"https://www.espncricinfo.com/series/ipl-2026-1510719/royal-challengers-bengaluru-squad-1511134/series-squads",
  "srh":"https://www.espncricinfo.com/series/ipl-2026-1510719/sunrisers-hyderabad-squad-1511114/series-squads"
  }
player_id_dict = {}
for url in squad_urls.values():
  url = (
        f"http://api.scraperapi.com/?api_key={os.environ['SCRAPER_API_KEY']}&url={url}"
    )
  page = requests.get(url)
  #page = requests.get(url, headers=headers)
  bs = BeautifulSoup(page.content, 'lxml')
  tabs = bs.find_all("div",{"class":"ds-grid lg:ds-grid-cols-2"})
  for tab in tabs:
    players = tab.find_all('a',href=True)
    for i in range(len(players)):
      if players[i].text.strip()!='':
        player_id_dict[players[i].text.strip()] = players[i].get("href").split("cricketers/")[1].split("-")[-1]